---
- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_1_id }} | Reset Rule Result to default value"
  ansible.builtin.set_fact:
    mysql57cis_rule_result: "FAILED"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_1_id }} | Set Fact Rule ID"
  ansible.builtin.set_fact:
    mysql_cis_rule_id: "{{ mysql57cis_rule_7_1_id | default('Missing Rule ID') }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_1_id }} | Set Fact Rule Name"
  ansible.builtin.set_fact:
    mysql_cis_rule_name: "{{ mysql57cis_rule_7_1_name }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_1_id }} | AUDIT | {{ mysql_cis_rule_name }}"
  tags:
    - audit
    - level1-mysql
    - rule_7.1
  when: 
    - mysql57cis_rule_7_1
  block:
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Gather plugin info"
      community.mysql.mysql_query:
        query: SHOW VARIABLES WHERE Variable_name = 'default_authentication_plugin'
      register: current_default_authentication_plugin

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Select value from query"
      ansible.builtin.set_fact:
        current_default_authentication_plugin: "{{ (current_default_authentication_plugin['query_result'] | flatten | map(attribute='Value')) | first }}"
      when:
        - current_default_authentication_plugin['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Compare plugin value"
      ansible.builtin.debug:
        msg: "Current 'default_authentication_plugin' plugin query results does not meet the minimum requirement of the benchmark. Result should not be 'mysql_native_password' for query."
      when:
        - not current_default_authentication_plugin == mysql57cis_default_authentication_plugin or
          current_default_authentication_plugin['query_result'] | flatten | length == 0 or
          current_default_authentication_plugin == "mysql_native_password"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql57cis_rule_result: "PASSED"
      when: 
        - current_default_authentication_plugin == mysql57cis_default_authentication_plugin
    
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql_cis_rule_result: "{{ mysql57cis_rule_result }}"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to WARNING Report"
      ansible.builtin.include_tasks:
        file: warning-audit-report.yml
      when:
        - not current_default_authentication_plugin == mysql57cis_default_authentication_plugin or
          current_default_authentication_plugin['query_result'] | flatten | length == 0 or
          current_default_authentication_plugin == "mysql_native_password"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to FULL Report"
      ansible.builtin.include_tasks:
        file: full-report.yml
...