---
- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_4_id }} | Reset Rule Result to default value"
  ansible.builtin.set_fact:
    mysql57cis_rule_result: "FAILED"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_4_id }} | Set Fact Rule ID"
  ansible.builtin.set_fact:
    mysql_cis_rule_id: "{{ mysql57cis_rule_7_4_id | default('Missing Rule ID') }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_4_id }} | Set Fact Rule Name"
  ansible.builtin.set_fact:
    mysql_cis_rule_name: "{{ mysql57cis_rule_7_4_name }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_4_id }} | AUDIT | {{ mysql_cis_rule_name }}"
  tags:
    - audit
    - level1-mysql
    - rule_7.4
  when: 
    - mysql57cis_rule_7_4
  block:
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Gather account info"
      community.mysql.mysql_query:
        query: SELECT User,host FROM mysql.user WHERE (plugin IN('mysql_native_password', 'mysql_old_password','') AND (LENGTH(authentication_string) = 0 OR authentication_string IS NULL))
      register: current_accounts_with_no_passwords
    
    # - ansible.builtin.debug:
    #     var: current_accounts_with_no_passwords

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Select value from query"
      ansible.builtin.set_fact:
        current_accounts_with_no_passwords: "{{ (current_accounts_with_no_passwords['query_result'] | flatten | map(attribute='Value')) | first }}"
      when:
        - current_accounts_with_no_passwords['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Check query results"
      ansible.builtin.debug:
        msg: "Current query results does not meet the minimum requirement of the benchmark. Result should return empty for query, all user passwords are set."
      when:
        - current_accounts_with_no_passwords['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql57cis_rule_result: "PASSED"
      when: 
        - current_accounts_with_no_passwords['query_result'] | flatten | length == 0
    
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql_cis_rule_result: "{{ mysql57cis_rule_result }}"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to WARNING Report"
      ansible.builtin.include_tasks:
        file: warning-audit-report.yml
      when:
        - current_accounts_with_no_passwords['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_7_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to FULL Report"
      ansible.builtin.include_tasks:
        file: full-report.yml
...