---
- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_4_id }} | Reset Rule Result to default value"
  ansible.builtin.set_fact:
    mysql57cis_rule_result: "FAILED"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_4_id }} | Set Fact Rule ID"
  ansible.builtin.set_fact:
    mysql_cis_rule_id: "{{ mysql57cis_rule_9_4_id | default('Missing Rule ID') }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_4_id }} | Set Fact Rule Name"
  ansible.builtin.set_fact:
    mysql_cis_rule_name: "{{ mysql57cis_rule_9_4_name }}"

- name: "MySQL {{ mysql_ver_maj_min }} {{ mysql57cis_rule_9_4_id }}  | AUDIT | {{ mysql_cis_rule_name }}"
  tags:
    - audit
    - level1-mysql
    - rule_9.4
  when: 
    - mysql57cis_rule_9_4
  block:
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Gather SSL Cert info"
      community.mysql.mysql_query:
        query: SELECT user, host FROM mysql.user WHERE user='repl' AND Super_priv = 'Y'
      register: current_super_priv_users

    # - ansible.builtin.debug:
    #     var: current_super_priv_users
    
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Select value from query"
      ansible.builtin.set_fact:
        current_super_priv_users: "{{ (current_super_priv_users['query_result'] | flatten | map(attribute='Value')) | first }}"
      when:
        - current_super_priv_users['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Compare query output"
      ansible.builtin.debug:
        msg: "Current results does not meet the minimum requirement of no rows returned. Ensure super_priv is not set to 'Y' for replicated users."
      when: 
        - current_super_priv_users['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql57cis_rule_result: "PASSED"
      when:
        - current_super_priv_users['query_result'] | flatten | length == 0
    
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql_cis_rule_result: "{{ mysql57cis_rule_result }}"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to WARNING Report"
      ansible.builtin.include_tasks:
        file: warning-audit-report.yml
      when:
        - current_super_priv_users['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to FULL Report"
      ansible.builtin.include_tasks:
        file: full-report.yml
...