---
- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_5_id }} | Reset Rule Result to default value"
  ansible.builtin.set_fact:
    mysql57cis_rule_result: "FAILED"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_5_id }} | Set Fact Rule ID"
  ansible.builtin.set_fact:
    mysql_cis_rule_id: "{{ mysql57cis_rule_9_5_id | default('Missing Rule ID') }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_5_id }} | Set Fact Rule Name"
  ansible.builtin.set_fact:
    mysql_cis_rule_name: "{{ mysql57cis_rule_9_5_name }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_5_id }}  | AUDIT | {{ mysql_cis_rule_name }}"
  tags:
    - audit
    - level1-mysql
    - rule_9.5
  when: 
    - mysql57cis_rule_9_5
  block:
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_5_id }} | AUDIT | {{ mysql_cis_rule_name }} | Gather SSL Cert info"
      community.mysql.mysql_query:
        query: SELECT user,host FROM mysql.user WHERE user = 'repl' AND host = '%'
      register: current_replicated_users

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_5_id }} | AUDIT | {{ mysql_cis_rule_name }} | Check query results"
      ansible.builtin.debug:
        msg: "Current query results does not meet the minimum requirement of the benchmark. Result should return empty for query, no rows should return."
      when:
        - current_replicated_users['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_5_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql57cis_rule_result: "PASSED"
      when:
        - current_replicated_users['query_result'] | flatten | length == 0
    
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_5_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql_cis_rule_result: "{{ mysql57cis_rule_result }}"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_5_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to WARNING Report"
      ansible.builtin.include_tasks:
        file: warning-audit-report.yml
      when:
        - current_replicated_users['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_5_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to FULL Report"
      ansible.builtin.include_tasks:
        file: full-report.yml
...