---
- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_2_id }} | Reset Rule Result to default value"
  ansible.builtin.set_fact:
    mysql57cis_rule_result: "FAILED"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_2_id }} | Set Fact Rule ID"
  ansible.builtin.set_fact:
    mysql_cis_rule_id: "{{ mysql57cis_rule_9_2_id | default('Missing Rule ID') }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_2_id }} | Set Fact Rule Name"
  ansible.builtin.set_fact:
    mysql_cis_rule_name: "{{ mysql57cis_rule_9_2_name }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_2_id }} | AUDIT | {{ mysql_cis_rule_name }}"
  tags:
    - audit
    - level1-mysql
    - rule_9.2
  when: 
    - mysql57cis_rule_9_2
  block:
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_2_id }} | AUDIT | {{ mysql_cis_rule_name }} | Gather SSL Cert info"
      community.mysql.mysql_query:
        query: SELECT ssl_verify_server_cert from mysql.slave_master_info
      register: current_master_ssl_cert

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_2_id }} | AUDIT | {{ mysql_cis_rule_name }} | Select value from query"
      ansible.builtin.set_fact:
        current_master_ssl_cert: "{{ (current_master_ssl_cert['query_result'] | flatten | map(attribute='Value')) | first }}"
      when:
        - current_master_ssl_cert['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_2_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql57cis_rule_result: "PASSED"
      when: 
        - current_master_ssl_cert == "1"
    
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_2_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql_cis_rule_result: "{{ mysql57cis_rule_result }}"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_2_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to WARNING Report"
      ansible.builtin.include_tasks:
        file: warning-audit-report.yml
      when:
        - not current_master_ssl_cert == "1"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_9_2_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to FULL Report"
      ansible.builtin.include_tasks:
        file: full-report.yml
...