---
- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_4_id }} | Reset Rule Result to default value"
  ansible.builtin.set_fact:
    mysql57cis_rule_result: "FAILED"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_4_id }} | Set Fact Rule ID"
  ansible.builtin.set_fact:
    mysql_cis_rule_id: "{{ mysql57cis_rule_4_4_id | default('Missing Rule ID') }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_4_id }} | Set Fact Rule Name"
  ansible.builtin.set_fact:
    mysql_cis_rule_name: "{{ mysql57cis_rule_4_4_name }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_4_id }} | AUDIT | {{ mysql_cis_rule_name }}"
  tags:
    - audit
    - level1-mysql
    - rule_4.4
  when:
    - mysql57cis_rule_4_4
  block:
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Gather harden usage info"
      community.mysql.mysql_query:
        query: SHOW VARIABLES WHERE Variable_name = 'local_infile'
      register: current_local_infile
    
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Select value from query"
      ansible.builtin.set_fact:
        current_local_infile: "{{ (current_local_infile['query_result'] | flatten | map(attribute='Value')) | first }}"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql57cis_rule_result: "PASSED"
      when: 
        - current_local_infile == mysql57cis_local_infile
    
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql_cis_rule_result: "{{ mysql57cis_rule_result }}"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to WARNING Report"
      ansible.builtin.include_tasks:
        file: warning-audit-report.yml
      when: 
        - not current_local_infile == mysql57cis_local_infile

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_4_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to FULL Report"
      ansible.builtin.include_tasks:
        file: full-report.yml
...