---
- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | Reset Rule Result to default value"
  ansible.builtin.set_fact:
    mysql57cis_rule_result: "FAILED"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | Set Fact Rule ID"
  ansible.builtin.set_fact:
    mysql_cis_rule_id: "{{ mysql57cis_rule_4_7_id | default('Missing Rule ID') }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | Set Fact Rule Name"
  ansible.builtin.set_fact:
    mysql_cis_rule_name: "{{ mysql57cis_rule_4_7_name }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | AUDIT | {{ mysql_cis_rule_name }} "
  tags:
    - audit
    - level1-mysql
    - rule_4.7
  when:
    - mysql57cis_rule_4_7
  block:
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | AUDIT | {{ mysql_cis_rule_name }} | Gather plugin is disabled info"
      community.mysql.mysql_query:
        query: SHOW DATABASES LIKE 'innodb_memcache'
      register: current_innodb_memcache

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | AUDIT | {{ mysql_cis_rule_name }} | Select value from query"
      ansible.builtin.set_fact:
        current_innodb_memcache: "{{ (current_innodb_memcache['query_result'] | flatten | map(attribute='Value')) | first }}"
      when:
        - current_innodb_memcache['query_result'] | flatten | length > 0

    # - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | AUDIT | {{ mysql_cis_rule_name }} | Compare plugin value"
    #   ansible.builtin.debug:
    #     msg: "Plugin 'daemon_memcached' is currently set as {{ current_innodb_memcache }}, which does not meet the benchmark requirement of {{ mysql57cis_innodb_memcache }}."
    #   when: not current_innodb_memcache == mysql57cis_innodb_memcache
    
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | AUDIT | {{ mysql_cis_rule_name }} | Compare plugin value"
      ansible.builtin.debug:
        msg: "Current innodb_memcached plugin does not meet the minimum requirement of no rows returned. Uninstall daemon_memcached plugin."
      when: 
        - current_innodb_memcache['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql57cis_rule_result: "PASSED"
      when:
        - current_innodb_memcache['query_result'] | flatten | length == 0
    
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql_cis_rule_result: "{{ mysql57cis_rule_result }}"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to WARNING Report"
      ansible.builtin.include_tasks:
        file: warning-audit-report.yml
      when:
        - current_innodb_memcache['query_result'] | flatten | length > 0

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_4_7_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to FULL Report"
      ansible.builtin.include_tasks:
        file: full-report.yml
...