---
- name: "SECTION | {{ mysql57cis_rule_4_4_id }} | {{ mysql57cis_rule_4_4_name }}"
  ansible.builtin.include_tasks: cis_4.4.yml
  vars:
    mysql57cis_rule_4_4_name: "Harden Usage for 'local_infile' on MySQL Clients"
  when:
    - mysql57cis_rule_4_4
  tags:
    - mysql57cis_rule_4_4

- name: "SECTION | {{ mysql57cis_rule_4_6_id }} | {{ mysql57cis_rule_4_6_name }}"
  ansible.builtin.include_tasks: cis_4.6.yml
  vars:
    mysql57cis_rule_4_6_name: "Ensure Symbolic Links are Disabled"
  when:
    - mysql57cis_rule_4_6
  tags:
    - mysql57cis_rule_4_6

- name: "SECTION | {{ mysql57cis_rule_4_7_id }} | {{ mysql57cis_rule_4_7_name }}"
  ansible.builtin.include_tasks: cis_4.7.yml
  vars:
    mysql57cis_rule_4_7_name: "Ensure the 'daemon_memcached' Plugin Is Disabled"
  when:
    - mysql57cis_rule_4_7
  tags:
    - mysql57cis_rule_4_7

- name: "SECTION | {{ mysql57cis_rule_4_8_id }} | {{ mysql57cis_rule_4_8_name }}"
  ansible.builtin.include_tasks: cis_4.8.yml
  vars:
    mysql57cis_rule_4_8_name: "Ensure the 'secure_file_priv' is Configured Correctly"
  when:
    - mysql57cis_rule_4_8
  tags:
    - mysql57cis_rule_4_8
...