---
- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_6_1_id }} | Reset Rule Result to default value"
  ansible.builtin.set_fact:
    mysql57cis_rule_result: "FAILED"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_6_1_id }} | Set Fact Rule ID"
  ansible.builtin.set_fact:
    mysql_cis_rule_id: "{{ mysql57cis_rule_6_1_id | default('Missing Rule ID') }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_6_1_id }} | Set Fact Rule Name"
  ansible.builtin.set_fact:
    mysql_cis_rule_name: "{{ mysql57cis_rule_6_1_name }}"

- name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_6_1_id }} | AUDIT | {{ mysql_cis_rule_name }}"
  tags:
    - audit
    - level1-mysql
    - rule_6.1
  when: 
    - mysql57cis_rule_6_1
  block:
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_6_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Gather log info"
      community.mysql.mysql_query:
        query: SHOW variables LIKE 'log_error'
      register: current_log_error

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_6_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Select value from query"
      ansible.builtin.set_fact:
        current_log_error: "{{ (current_log_error['query_result'] | flatten | map(attribute='Value')) | first }}"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_6_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Compare value with benchmark"
      ansible.builtin.debug:
        msg: "Current 'log_error' parameter, {{ current_log_error }}, does not meet the minimum benchmark requirement of '{{ mysql57cis_log_error }}'."
      when: 
        - not current_log_error == mysql57cis_log_error

    # NEED TO CHECK FOR 'stderr'
    # Default vaulue is 'stderr' and is a fail
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_6_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql57cis_rule_result: "PASSED"
      when: 
        - current_log_error == mysql57cis_log_error
    
    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_6_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Set Rule Result"
      ansible.builtin.set_fact:
        mysql_cis_rule_result: "{{ mysql57cis_rule_result }}"

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_6_1_id }} | AUDIT | {{ mysql_cis_rule_name }} | Add {{ mysql_cis_rule_id }} result to WARNING Report"
      ansible.builtin.include_tasks:
        file: warning-audit-report.yml
      when:
        - not current_log_error == mysql57cis_log_error

    - name: "MySQL {{ mysql_ver_maj_min }} CIS {{ mysql57cis_rule_6_1_id }} | AUDIT | Add {{ mysql_cis_rule_id }} result to FULL Report"
      ansible.builtin.include_tasks:
        file: full-report.yml
...